### ISSUE TITLE
Samplemixer/groovewrap -- old stereo playing as mono bug in groovewrap?

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-MMJ-Depot#57]
I was checking the samplemixer standalone and found that stereo files played out as mono.  The "panning" in groovewrap object does move the summed stereo files to l/r.  But the files themselves are playing in mono.  This is a very old bug and it was reported fixed several times in the past.  Once fixed, we will need a new samplemixer standalone.

**Comment by equilet** [comment]
I think it might be the case that this was fixed in the depot and not in the standalones.  I'll do some testing to figure that out...

**Comment by equilet** [comment]
The issue I am seeing in the depot is that the panning is functional for groovewrap, but that the reverb wasn't properly panning to the correct channels.  I've fixed this by disabling the appropriate signal outputs for audio output.  I can roll this change into the upcoming release of the standalones.

**Comment by EdmundCampion** [comment]
Here are a number of things from my testdrive of 4/3/15

Stereo files are still not playing back in stereo.  I am sending you a file on e-mail to test with.  The problem is that you must have a file where L/R are clear and distinguished -- I am sending you test-stereo_test.aif

Notice that the waveform display only shows image of mono soundfile (doubled in stereo view).  With this soundfile you can clearly hear that both sounds (even with reverb turned down to zero) are being mixed into L/R output.


There is a problem with the LOOP MODE and Waveform Seleciton.  It really involves two separate things that need to be clarified.  1)  selecting portion of audio in waveform window for playback, and 2) looping the selected portion of audio)

I think the simple solution is to add a feature to groovewrap that "clears" selection -- this will return the selection in the waveform window to playback complete waveform, and it will zero out the loop numbers.

Then, for the Loop mode part

LOOP MODE --
The LOOP MODE toggle outside the groovewrap (samplemixer patch) should just be a global on/off.  Each groovewrap should always show the Loop Mode state with the default Loop/Selection Mode state OFF.  

GAIN SLIDER PROBLEM:  The gain slider has been adjusted with more headroom.  This makes the audio output when moving the gain slider to half-position already mostly inaudible (-69).  See if you can improve on the gain function in terms of visual length of slider and overall gain perception.

MP3 enabled?  Can we upgrade groovewrap to allow for MP3 without any time spent on it?

Move the "clear" message to just below the "drop folder containing soundfiles" window.  and change text to "clear all soundfiles from memory.


 





When checked, the groovewrap Loop Mode should work just as it does -- the window selection is enabled default playback always being "play the entire file whenever play is initiated.

The gain slider for groovewrap has been augmented in range, but it woul

**Comment by equilet** [comment]
"looping back" to this.

I just did a simple test in the depot with the current revision of sample mixer and everthing is fine there in terms of playing back stereo files.  groovewrap~ was the culprit.  

If you can go ahead and test this for verification, I'd appreciate it, but I think this is now primed for a samplemixer update.

Because this issue has become cluttered, I'm going to open a new one with the other items you've mentioned here.
